# Generated by Django 3.0.7 on 2020-07-06 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('icon', models.ImageField(default='user-profile.png', upload_to='')),
                ('feature_01', models.CharField(max_length=200)),
                ('feature_02', models.CharField(max_length=200)),
                ('feature_03', models.CharField(max_length=200)),
                ('feature_04', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('ordered_date', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('subscription_plan', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='store.Item')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='store.Visitor')),
            ],
        ),
    ]
